language: node_js
node_js: 
    - '6'

# Travis-CI Caching
cache:
  directories:
    - dist/demo/default/node_modules

# S: Build Lifecycle
install:
  - cd dist/demo/default/
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - cd ./dist/demo/default/
  - npm run build

after_script:
# E: Build LifeCycle